name: mimi_select_product_list_project
description: "Mimi Select: A Flutter application for fetching and displaying product with API."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  connectivity_plus: ^7.0.0
  loading_animation_widget: ^1.3.0
  dio: ^5.9.0
  pull_to_refresh_flutter3: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 
  flutter_launcher_icons: ^0.14.4 

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon_app.png"
  min_sdk_android: 21 # แนะนำ 21 ขึ้นไปสำหรับแอปสมัยใหม่
  web:
    generate: true
    image_path: "assets/icon/icon_app.png"
    background_color: "#C0212F"
    theme_color: "#ffffff"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/

  fonts:
    - family: Mitr
      fonts:
        - asset: assets/fonts/Mitr-Regular.ttf
        - asset: assets/fonts/Mitr-Bold.ttf
        - asset: assets/fonts/Mitr-Light.ttf
        - asset: assets/fonts/Mitr-Medium.ttf
